# -*- coding: utf-8 -*-
"""Salinan dari Selamat Datang di Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHHDES3M_kDa820HtRY0suApcaTq3deB
"""

# ============================================================
# api.py
# WorkSafe AI - REST API (Flask)
# jalankan: python api.py
# ============================================================
from flask import Flask, request, jsonify
import numpy as np
import pandas as pd
import pickle
import tensorflow as tf
from tensorflow import keras

app = Flask(__name__)

PATH_MODEL    = './models/worksafe_model_v1.keras'
PATH_SCALER   = './models/scaler.pkl'
PATH_IMPUTER  = './models/imputer.pkl'
PATH_FEATURES = './models/feature_cols.pkl'

# ============================================================
# FOCAL LOSS
# ============================================================
class FocalLoss(keras.losses.Loss):
    def __init__(self, gamma=2.0, alpha=0.25, name='focal_loss', **kwargs):
        super().__init__(name=name, **kwargs)
        self.gamma = gamma
        self.alpha = alpha

    def call(self, y_true, y_pred):
        y_true    = tf.cast(tf.reshape(y_true, [-1]), tf.int32)
        y_true_oh = tf.cast(tf.one_hot(y_true, depth=3), tf.float32)
        y_pred    = tf.cast(y_pred, tf.float32)
        y_pred    = tf.clip_by_value(y_pred, 1e-7, 1.0 - 1e-7)
        ce           = -y_true_oh * tf.math.log(y_pred)
        p_t          = tf.reduce_sum(y_true_oh * y_pred, axis=-1, keepdims=True)
        focal_weight = tf.pow(1.0 - p_t, self.gamma)
        loss         = self.alpha * focal_weight * tf.reduce_sum(ce, axis=-1)
        return tf.reduce_mean(loss)

    def get_config(self):
        cfg = super().get_config()
        cfg.update({'gamma': self.gamma, 'alpha': self.alpha})
        return cfg

# ============================================================
# LOAD SEMUA ARTIFACT SAAT SERVER NYALA
# ============================================================
model = keras.models.load_model(
    PATH_MODEL,
    custom_objects={'FocalLoss': FocalLoss}
)
with open(PATH_SCALER,   'rb') as f: scaler       = pickle.load(f)
with open(PATH_IMPUTER,  'rb') as f: imputer      = pickle.load(f)
with open(PATH_FEATURES, 'rb') as f: feature_cols = pickle.load(f)

LABEL_MAP = {0: 'Low Risk', 1: 'Medium Risk', 2: 'High Risk'}

median_values = {
    col: float(imputer.statistics_[i])
    for i, col in enumerate(feature_cols)
}

print("Model loaded. Server siap.")

# ============================================================
# FUNGSI PREPROCESSING
# ============================================================
def preprocess(input_dict):
    df = pd.DataFrame([input_dict])
    for col in feature_cols:
        if col not in df.columns:
            df[col] = np.nan
    df     = df[feature_cols]
    df_imp = pd.DataFrame(
        imputer.transform(df),
        columns=feature_cols
    )
    df_scaled = pd.DataFrame(
        scaler.transform(df_imp),
        columns=feature_cols
    )
    return df_scaled.values.astype(np.float32)

# ============================================================
# ROUTES
# ============================================================

# cek server hidup atau tidak
@app.route('/', methods=['GET'])
def root():
    return jsonify({
        'message': 'WorkSafe AI API aktif',
        'version': '1.0.0'
    })

# endpoint utama prediksi
@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.get_json()

        if not data or 'features' not in data:
            return jsonify({'error': 'Key features tidak ditemukan'}), 400

        # isi fitur yang tidak dikirim dengan nilai median
        full_input = {col: median_values[col] for col in feature_cols}
        full_input.update(data['features'])

        X     = preprocess(full_input)
        proba = model.predict(X, verbose=0)[0]
        kelas = int(np.argmax(proba))

        return jsonify({
            'risk_label'   : LABEL_MAP[kelas],
            'risk_class'   : kelas,
            'confidence'   : round(float(proba[kelas]) * 100, 2),
            'probabilities': {
                'Low Risk'   : round(float(proba[0]) * 100, 2),
                'Medium Risk': round(float(proba[1]) * 100, 2),
                'High Risk'  : round(float(proba[2]) * 100, 2),
            }
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500

# endpoint untuk lihat daftar fitur yang dibutuhkan model
@app.route('/features', methods=['GET'])
def get_features():
    return jsonify({
        'total_features': len(feature_cols),
        'feature_list'  : list(feature_cols)
    })

# ============================================================
# JALANKAN SERVER
# ============================================================
if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)